
import { Card } from '@/components/ui/card';

const HowItWorksPage = () => {
  return (
    <div className="min-h-screen bg-gray-50 pt-24 pb-16">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold text-deepblue mb-4 text-center">
            How Our DeepFake Detection Works
          </h1>
          <p className="text-lg text-gray-600 mb-12 text-center">
            Understanding the technology behind our AI-powered media analysis
          </p>
          
          <Card className="p-8 mb-12">
            <h2 className="text-2xl font-semibold text-deepblue mb-6">The Technology Behind the Detection</h2>
            <div className="space-y-6">
              <div className="flex gap-4">
                <div className="bg-teal-100 text-teal-600 rounded-full h-8 w-8 flex items-center justify-center flex-shrink-0 mt-1">
                  1
                </div>
                <div>
                  <h3 className="text-xl font-medium text-deepblue mb-2">Advanced Neural Networks</h3>
                  <p className="text-gray-600">
                    Our technology uses convolutional neural networks (CNNs) and transformers that have been trained on millions of real and AI-generated images and videos. These networks learn to identify subtle patterns that distinguish AI-generated content from authentic media.
                  </p>
                </div>
              </div>
              
              <div className="flex gap-4">
                <div className="bg-teal-100 text-teal-600 rounded-full h-8 w-8 flex items-center justify-center flex-shrink-0 mt-1">
                  2
                </div>
                <div>
                  <h3 className="text-xl font-medium text-deepblue mb-2">Multi-layer Analysis</h3>
                  <p className="text-gray-600">
                    Our system performs analysis at multiple levels: pixel-level inconsistencies, facial feature anomalies, lighting and shadow irregularities, and metadata verification. This comprehensive approach ensures high accuracy.
                  </p>
                </div>
              </div>
              
              <div className="flex gap-4">
                <div className="bg-teal-100 text-teal-600 rounded-full h-8 w-8 flex items-center justify-center flex-shrink-0 mt-1">
                  3
                </div>
                <div>
                  <h3 className="text-xl font-medium text-deepblue mb-2">Continuous Learning</h3>
                  <p className="text-gray-600">
                    As AI generation techniques evolve, so does our detection technology. Our models are regularly updated with the latest deepfake examples to ensure they stay effective against new generation methods.
                  </p>
                </div>
              </div>
            </div>
          </Card>
          
          <div className="grid md:grid-cols-2 gap-6 mb-12">
            <Card className="p-6">
              <h3 className="text-xl font-semibold text-deepblue mb-4">What We Can Detect</h3>
              <ul className="space-y-3 text-gray-600">
                <li className="flex items-start gap-2">
                  <span className="text-teal-500 font-bold">✓</span>
                  <span>AI-generated faces and manipulated facial features</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-teal-500 font-bold">✓</span>
                  <span>Inconsistencies in lighting, shadows, and reflections</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-teal-500 font-bold">✓</span>
                  <span>Unnatural blending and warping of images</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-teal-500 font-bold">✓</span>
                  <span>Face swaps and digital composites</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-teal-500 font-bold">✓</span>
                  <span>Content generated by popular AI image generators</span>
                </li>
              </ul>
            </Card>
            
            <Card className="p-6">
              <h3 className="text-xl font-semibold text-deepblue mb-4">Accuracy & Limitations</h3>
              <p className="text-gray-600 mb-4">
                Our technology achieves 95%+ accuracy for high-quality images and videos. However, there are some limitations:
              </p>
              <ul className="space-y-3 text-gray-600">
                <li className="flex items-start gap-2">
                  <span className="text-amber-500 font-bold">⚠</span>
                  <span>Heavily compressed or low-resolution media may yield less certain results</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-amber-500 font-bold">⚠</span>
                  <span>Very sophisticated deepfakes may occasionally evade detection</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-amber-500 font-bold">⚠</span>
                  <span>Unique or unusual genuine content might be flagged for manual review</span>
                </li>
              </ul>
            </Card>
          </div>
          
          <div className="bg-white rounded-lg p-8 shadow-md border border-gray-100">
            <h2 className="text-2xl font-semibold text-deepblue mb-4">The Analysis Process</h2>
            
            <div className="relative">
              {/* Timeline line */}
              <div className="absolute left-8 top-0 bottom-0 w-0.5 bg-gray-200"></div>
              
              <div className="space-y-8">
                <div className="flex gap-6 relative">
                  <div className="w-16 h-16 rounded-full bg-teal-500 text-white flex items-center justify-center flex-shrink-0 z-10">
                    1
                  </div>
                  <div className="pt-3">
                    <h3 className="text-xl font-medium text-deepblue mb-2">Media Upload</h3>
                    <p className="text-gray-600">
                      You upload an image or video to our secure platform. Your media is encrypted in transit and during processing to protect your privacy.
                    </p>
                  </div>
                </div>
                
                <div className="flex gap-6 relative">
                  <div className="w-16 h-16 rounded-full bg-teal-500 text-white flex items-center justify-center flex-shrink-0 z-10">
                    2
                  </div>
                  <div className="pt-3">
                    <h3 className="text-xl font-medium text-deepblue mb-2">Initial Screening</h3>
                    <p className="text-gray-600">
                      Our system analyzes basic properties of your media, including metadata, resolution, and format. It prepares the content for deeper analysis.
                    </p>
                  </div>
                </div>
                
                <div className="flex gap-6 relative">
                  <div className="w-16 h-16 rounded-full bg-teal-500 text-white flex items-center justify-center flex-shrink-0 z-10">
                    3
                  </div>
                  <div className="pt-3">
                    <h3 className="text-xl font-medium text-deepblue mb-2">Deep Analysis</h3>
                    <p className="text-gray-600">
                      Our neural networks analyze your media for telltale signs of AI generation or manipulation. For images, this takes seconds; for videos, processing time depends on length and complexity.
                    </p>
                  </div>
                </div>
                
                <div className="flex gap-6 relative">
                  <div className="w-16 h-16 rounded-full bg-teal-500 text-white flex items-center justify-center flex-shrink-0 z-10">
                    4
                  </div>
                  <div className="pt-3">
                    <h3 className="text-xl font-medium text-deepblue mb-2">Results & Report</h3>
                    <p className="text-gray-600">
                      You receive a detailed analysis showing the probability that the media is AI-generated, along with a visualization of areas that raised flags in our system.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HowItWorksPage;
